FROM cirrusci/flutter:2.5.3 as build

WORKDIR /src

RUN flutter precache --no-linux

COPY . .

RUN flutter pub get

RUN flutter build web

FROM nginx:1.21.4 as final

COPY --from=build /src/build/web /usr/share/nginx/html
